# Generated by rust2rpm 24
%bcond_without check

%global crate chainsaw

Name:           rust-chainsaw
Version:        2.13.1
Release:        %autorelease
Summary:        Rapidly Search and Hunt through Windows Forensic Artefacts

License:        GPL-3.0-or-later
URL:            https://github.com/WithSecureLabs/chainsaw/
# Source0:        https://github.com/WithSecureLabs/chainsaw/releases/tag/v%{version}#/%{name}-%{version}.tar.gz
Source0:        https://github.com/WithSecureLabs/chainsaw/archive/v%{version}.tar.gz#/%{name}-%{version}.tar.gz

BuildRequires:  rust-packaging >= 21
BuildRequires:  rust-aho-corasick+default-devel
BuildRequires:  rust-anyhow+default-devel 
BuildRequires:  rust-assert_cmd+default-devel 
BuildRequires:  rust-bincode+default-devel
BuildRequires:  rust-bytesize+default-devel
BuildRequires:  rust-chrono-tz+default-devel
BuildRequires:  rust-chrono-tz+serde-devel
BuildRequires:  rust-chrono+default-devel
BuildRequires:  rust-clap+default-devel
BuildRequires:  rust-clap+derive-devel
BuildRequires:  rust-colour+default-devel
BuildRequires:  rust-evtx+default-devel
BuildRequires:  rust-indicatif+default-devel
BuildRequires:  rust-mft+default-devel
BuildRequires:  rust-paste+default-devel
BuildRequires:  rust-predicates+default-devel
BuildRequires:  rust-prettytable-rs+default-devel
BuildRequires:  rust-quick-xml+default-devel
BuildRequires:  rust-rayon+default-devel
BuildRequires:  rust-regex+default-devel
BuildRequires:  rust-rustc-hash+default-devel
BuildRequires:  rust-serde+derive-devel
#BuildRequires:  
BuildRequires:  rust-serde_json+default-devel
BuildRequires:  rust-serde_yaml+default-devel
BuildRequires:  rust-term_size+default-devel
BuildRequires:  rust-tau_engine+sync-devel
BuildRequires:  rust-tau_engine+json-devel
BuildRequires:  rust-tau_engine+core-devel
BuildRequires:  rust-tau_engine+default-devel
BuildRequires:  rust-uuid+v4-devel
BuildRequires:  rust-uuid+serde-devel
BuildRequires:  rust-uuid+default-devel


%global _description %{expand:
Chainsaw provides a powerful ‘first-response’ capability to quickly identify
threats within Windows forensic artefacts such as Event Logs and MFTs.
Chainsaw offers a generic and fast method of searching through event logs for
keywords, and by identifying threats using built-in support for Sigma detection
rules, and via custom Chainsaw detection rules.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE
%doc CHANGELOG.md
%{_bindir}/chainsaw

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/CHANGELOG.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
