# Generated by go2rpm 1.9.0
%bcond_with		check
%global debug_package %{nil}

# https://github.com/pin/tftp
%global goipath         github.com/pin/tftp/v3
Version:                3.1.0

%gometa -f


%global common_description %{expand:
TFTP server and client library for Golang.}

%global golicenses      LICENSE
%global godocs          CONTRIBUTORS README.md

Name:           %{goname}
Release:        %autorelease
Summary:        TFTP server and client library for Golang

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -q -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog

