# Generated by rust2rpm 24
%bcond_without check

%global crate evtx

Name:           rust-evtx
Version:        0.8.1
Release:        %autorelease
Summary:        Fast (and safe) parser for the Windows XML Event Log (EVTX) format

# Upstream license specification: MIT/Apache-2.0
License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/evtx
Source:         %{crates_source}
# Automatically generated patch to strip foreign dependencies
Patch:          evtx-fix-metadata-auto.diff

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
A Fast (and safe) parser for the Windows XML Event Log (EVTX) format.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE-APACHE
%license LICENSE-MIT
%doc CHANGELOG.md
%doc README.md
%{_bindir}/evtx_dump

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+anyhow-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+anyhow-devel %{_description}

This package contains library source intended for building other packages which
use the "anyhow" feature of the "%{crate}" crate.

%files       -n %{name}+anyhow-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+clap-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+clap-devel %{_description}

This package contains library source intended for building other packages which
use the "clap" feature of the "%{crate}" crate.

%files       -n %{name}+clap-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+dialoguer-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+dialoguer-devel %{_description}

This package contains library source intended for building other packages which
use the "dialoguer" feature of the "%{crate}" crate.

%files       -n %{name}+dialoguer-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+evtx_dump-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+evtx_dump-devel %{_description}

This package contains library source intended for building other packages which
use the "evtx_dump" feature of the "%{crate}" crate.

%files       -n %{name}+evtx_dump-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+fast-alloc-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+fast-alloc-devel %{_description}

This package contains library source intended for building other packages which
use the "fast-alloc" feature of the "%{crate}" crate.

%files       -n %{name}+fast-alloc-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+indoc-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+indoc-devel %{_description}

This package contains library source intended for building other packages which
use the "indoc" feature of the "%{crate}" crate.

%files       -n %{name}+indoc-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+jemallocator-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+jemallocator-devel %{_description}

This package contains library source intended for building other packages which
use the "jemallocator" feature of the "%{crate}" crate.

%files       -n %{name}+jemallocator-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+multithreading-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+multithreading-devel %{_description}

This package contains library source intended for building other packages which
use the "multithreading" feature of the "%{crate}" crate.

%files       -n %{name}+multithreading-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rayon-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rayon-devel %{_description}

This package contains library source intended for building other packages which
use the "rayon" feature of the "%{crate}" crate.

%files       -n %{name}+rayon-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+simplelog-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+simplelog-devel %{_description}

This package contains library source intended for building other packages which
use the "simplelog" feature of the "%{crate}" crate.

%files       -n %{name}+simplelog-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires -f evtx_dump

%build
%cargo_build -f evtx_dump

%install
%cargo_install -f evtx_dump

%if %{with check}
%check
%cargo_test -f evtx_dump
%endif

%changelog
%{?%autochangelog: %autochangelog }
