# Generated by go2rpm 1
%bcond_with		check

# https://github.com/OJ/gobuster
%global goipath         github.com/OJ/gobuster/v3
Version:                3.5.0

%gometa

%global common_description %{expand:
Directory/File, DNS and VHost busting tool written in Go.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           gobuster
Release:        %autorelease
Summary:        Directory/File, DNS and VHost busting tool written in Go

License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%build
%gobuild -o %{gobuilddir}/bin/gobuster %{goipath}

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc README.md
%{_bindir}/*

%gopkgfiles

%changelog
%{?%autochangelog: %autochangelog }
