Name:           httpdump
Version:        0
Release:        %autorelease
Summary:        Capture and parse http traffics
VCS:            https://github.com/hsiafan/httpdump


# Generated by go2rpm 1.18.0
%bcond check 1

# https://github.com/hsiafan/httpdump
%global goipath         github.com/hsiafan/httpdump
%global commit          4fd809447b593cc9e4420141691ec304b3fa4e9e
%global date            20231019

%gometa -L -f


# Generated by go-vendor-tools
License:        Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND ISC AND MIT
URL:            %{gourl}
Source0:        %{gosource}
# Generated by go-vendor-tools
Source1:        %{archivename}-vendor.tar.bz2
Source2:        go-vendor-tools.toml

BuildRequires:  go-vendor-tools
BuildRequires:  pkgconfig(libpcap)

%description
Capture and parse http traffic.

%prep
%goprep -A
%setup -q -T -D -a1 %{forgesetupargs}
%autopatch -p1

%generate_buildrequires
%go_vendor_license_buildrequires -c %{S:2}

%build
%global gomodulesmode GO111MODULE=on
%gobuild -o %{gobuilddir}/bin/httpdump %{goipath}
for cmd in httpport; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%go_vendor_license_install -c %{S:2}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%check
%go_vendor_license_check -c %{S:2}
%if %{with check}
%gotest ./...
%endif

%files -f %{go_vendor_license_filelist}
%license vendor/modules.txt
%doc README.md
%{_bindir}/httpdump
%{_bindir}/httpport


%changelog
%autochangelog
