# Generated by go2rpm 1
# Checks need a local web server to perform requests against
%bcond_with check
%global debug_package %{nil}


# https://github.com/projectdiscovery/retryablehttp-go
%global goipath         github.com/projectdiscovery/retryablehttp-go
Version:                1.0.2

%gometa

%global common_description %{expand:
Package retryablehttp provides a familiar HTTP client interface with automatic
retries and exponential backoff.}

%global golicenses      LICENSE.md
%global godocs          README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Familiar HTTP client interface

License:        MPL-2.0
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
