# Generated by go2rpm 1.8.2
%bcond_without check

# https://github.com/trufflesecurity/trufflehog
%global goipath         github.com/trufflesecurity/trufflehog
Version:                3.27.1

%gometa -f

%global common_description %{expand:
Find credentials all over the place.}

%global golicenses      LICENSE
%global godocs          SECURITY.md CODE_OF_CONDUCT.md README.md\\\
                        CONTRIBUTING.md pkg/detectors/words.txt\\\
                        pkg/detectors/badlist.txt\\\
                        pkg/detectors/programmingbooks.txt\\\
                        pkg/detectors/readme/readme.go\\\
                        pkg/detectors/readme/readme_test.go\\\
                        pkg/detectors/privatekey/rockyou-15.txt\\\
                        pkg/detectors/todoist/todoist_test.go\\\
                        pkg/detectors/todoist/todoist.go docs\\\
                        hack/snifftest/README.md

Name:           trufflehog
Release:        %autorelease
Summary:        Find credentials all over the place

License:        AGPL-3.0-only
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%build
%gobuild -o %{gobuilddir}/bin/trufflehog %{goipath}
for cmd in hack/generate hack/snifftest; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc SECURITY.md CODE_OF_CONDUCT.md README.md CONTRIBUTING.md
%doc pkg/detectors/words.txt pkg/detectors/badlist.txt
%doc pkg/detectors/programmingbooks.txt pkg/detectors/readme/readme.go
%doc pkg/detectors/readme/readme_test.go pkg/detectors/privatekey/rockyou-15.txt
%doc pkg/detectors/todoist/todoist_test.go pkg/detectors/todoist/todoist.go docs
%doc hack/snifftest/README.md
%{_bindir}/*

%gopkgfiles

%changelog
%{?%autochangelog: %autochangelog }
