dwarf2json.1:
	help2man dwarf2json --no-discard-stderr > dwarf2json.1
	help2man dwarf2json --help-option="linux --help" --no-discard-stderr >> dwarf2json.1
	help2man dwarf2json --help-option="mac --help" --no-discard-stderr >> dwarf2json.1
